name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (patch, minor, major, prepatch, preminor, premajor, alpha, beta, rc)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - alpha
          - beta
          - rc # Release Candidate

jobs:
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm clean-install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --release-type ${{ github.event.inputs.release_type }}
